# Server Configuration
server.port=8083

# Spring Application
spring.application.name=cabinet-service

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cabinet_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Security OAuth2 Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/cabinet-medical
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/cabinet-medical/protocol/openid-connect/certs

# ============================================
# STRIPE CONFIGURATION
# ============================================
stripe.api-key=sk_test_51Qve47GMvHZk4oqlfKzc8jLerUMtjoejB78ulyElRYpqtj2q5PEYf6DSFjFmaHAjwq4bkxlCIX8PcwM2iKOVjGtr00o7lrIeDT
stripe.webhook-secret=whsec_NjUbbP3VNe9Fq8sD4YBvpjGgNXMnkNK6

# Management Endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Logging Configuration
logging.level.com.cabinetmedical=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuration personnalisée
cabinet.abonnement.alerte-jours-avant-expiration=7
cabinet.abonnement.verification-cron=0 0 9 * * ?

# Application Configuration
application.config.utilisateur-url=http://localhost:8082/api/utilisateur/
