
# server port configuration
server.port=8082

# database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://localhost:5432/utilisateur_db

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Keycloak Configuration
keycloak.realm=cabinet-medical
keycloak.auth-server-url=http://localhost:9098
keycloak.resource=cabinet-medical-backend
keycloak.credentials.secret=P41YWxkqVDjxhe06l4oJ58kbYoK2fYbN
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.client-id=admin-cli

# Spring Security OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9098/realms/cabinet-medical
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9098/realms/cabinet-medical/protocol/openid-connect/certs





